accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('profile/<int:user_pk>/', views.profile, name='profile'),
    path('password/', views.change_password, name='change_password'),
    path('edit/', views.edit, name='edit'),
    path('delete/', views.delete, name='delete'),
    path('logout/', views.logout, name='logout'),
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),    
]

boards/urls.py
from django.urls import path
from . import views

app_name = 'boards'

urlpatterns = [
    path('<int:board_pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),    
    path('<int:board_pk>/comments/', views.comment_create, name='comment_create'),    
    path('<int:board_pk>/edit/', views.update, name='update'),    
    path('<int:board_pk>/delete/', views.delete, name='delete'),    
    path('<int:board_pk>/', views.detail, name='detail'),    
    path('new/', views.create, name='create'),    
    path('', views.index, name='index'),    
]

myform/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('boards/', include('boards.urls')),
    path('admin/', admin.site.urls),
]

boards/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Board(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f'Board{self.pk}'
        # return self.title

class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    content = models.CharField(max_length=140)
    
    def __str__(self):
        return self.content

boards/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from .models import Board, Comment
# class BoardForm(forms.Form):
#     title = forms.CharField(label='제목', widget=forms.TextInput(attrs={
#                                                     'placeholder': 'THE TITLE!!',
#                                           }))
#     content = forms.CharField(label='내용', 
#                               error_messages={'required': '제발 내용을 입력해주세요!'},
#                               widget=forms.Textarea(attrs={
#                                                     'class': 'Content-input',
#                                                     'rows': 5,
#                                                     'cols': 50,
#                                                     'placeholder': 'Fill the Content!',
#                                           }))
class BoardForm(forms.ModelForm):
    # Model 의 정보를 작성하는 곳
    class Meta:
        model = Board
        # models.py 에 지정해놓은 필드를 사용한다.
        fields = ['title', 'content',]
        widgets = {'title': forms.TextInput(attrs={
                                                'placeholder': '제목을 입력하세요.',
                                                'class': 'title',}),
                  'content': forms.Textarea(attrs={
                                                'placeholder': '내용을 입력하세요.',
                                                'class': 'content',
                                                'rows': 5,
                                                'cols': 50,})}
        # error_messages = {'title': {
        #                                 'required': '제발 입력해주세여.'
        #                           },
        #                   'content': {
        #                                 'required': '내용 입력하라고'
        #                   },
        #                 }
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'POST'
        self.helper.add_input(Submit('submit', '작성!'))


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content',]
    

boards/views.py
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from .models import Board, Comment
from .forms import BoardForm, CommentForm

# Create your views here.
def index(request):
    # boards = get_list_or_404(Board.objects.order_by('-pk'))
    boards = Board.objects.order_by('-pk')
    context = {
        'boards': boards,
    }
    return render(request, 'boards/index.html', context)


@login_required
def create(request):
    if request.method == 'POST':
        form = BoardForm(request.POST)
        if form.is_valid():
            # board 를 바로 저장하지 않고, 현재 user 를 넣고 저장
            # 실제 DB 에 반영 전까지의 단계를 진행하고, 그 중간에 user 정보를
            # request.user 에서 가져와서 그 후에 저장한다.
            board = form.save(commit=False)
            board.user = request.user
            board.save()
            return redirect('boards:detail', board.pk)
    else:
        form = BoardForm()
    context = {'form': form}
    return render(request, 'boards/form.html', context)


def detail(request, board_pk):
    board = get_object_or_404(Board, pk=board_pk)
    comment_form = CommentForm()
    context = {
        'board': board,
        'comment_form': comment_form,
    }
    return render(request, 'boards/detail.html', context)


def delete(request, board_pk):
    board = get_object_or_404(Board, pk=board_pk)
    if board.user == request.user:
        if request.method == 'POST':
            board.delete()
            return redirect('boards:index')
        else:
            return redirect('boards:detail', board.pk)
    else:
        return redirect('boards:index')


@login_required
def update(request, board_pk):
    board = get_object_or_404(Board, pk=board_pk)
    if board.user == request.user:
        if request.method == 'POST':
            form = BoardForm(request.POST, instance=board)   
            if form.is_valid():
                board = form.save()                         
                return redirect('boards:detail', board.pk)
        else:
            form = BoardForm(instance=board)            
    else:
        return redirect('boards:index')
    context = {
        'form': form,
        'board': board,
    }
    return render(request, 'boards/form.html', context)

@require_POST
@login_required
def comment_create(request, board_pk):
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.user = request.user
        comment.board_id = board_pk
        comment.save()
    return redirect('boards:detail', board_pk)

@require_POST
@login_required
def comment_delete(request, board_pk, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    comment.delete()
    return redirect('boards:detail', board_pk)

boards/templates/boards/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    <div class="container">
        {% if user.is_authenticated %}
            <h1>
                안녕, {{ user.username }}
                <a href="{% url 'accounts:profile' user.pk %}">[내프로필]</a>
                <a href="{% url 'accounts:logout' %}">[로그아웃]</a>
            </h1>
        {% else %}
            <h1>
                <a href="{% url 'accounts:login' %}">[로그인]</a>
                <a href="{% url 'accounts:signup' %}">[회원가입]</a>
            </h1>
        {% endif %}
        <hr>
        {% block body %}
        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

boards/templates/boards/detail.html
{% extends 'boards/base.html' %}
{% block body %}
{% load crispy_forms_tags %}

<h1>{{ board.pk }} 번째 글</h1>
<h2>{{ board.title }}</h2>
<hr>
<p>{{ board.content }}</p>
<!-- 댓글 출력 -->
{% for comment in board.comment_set.all %}
    <div>
        <b>{{ comment.user }}</b> : {{ comment.content }}
        {% if user == comment.user %}
            <form action="{% url 'boards:comment_delete' board.pk comment.pk %}" method="POST" style="display: inline;">
                {% csrf_token %}
                <input type="submit" value="삭제">
            </form>
        {% endif %}
    </div>
{% empty %}
    <div>댓글이 없습니다.</div>
{% endfor %}

<!-- 댓글 입력 창 -->
<hr>
{% if user.is_authenticated %}
    <form action="{% url 'boards:comment_create' board.pk %}" method="POST">
        {% csrf_token %}
        {{ comment_form|crispy }}
        <input type="submit" value="작성">
    </form>
{% else %}
    <a href="{% url 'accounts:login' %}">댓글을 작성하려면 로그인하세요.</a>
{% endif %}

<hr>

<a href="{% url 'boards:index' %}">BACK</a>

{% if user == board.user %}
    <form action="{% url 'boards:delete' board.pk %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="삭제">
    </form>
    <a href="{% url 'boards:update' board.pk %}">[수정]</a>
{% endif %}
{% endblock %}

boards/templates/boards/form.html
{% extends 'boards/base.html' %}
{% block body %}
{% load crispy_forms_tags %}

{% if request.resolver_match.url_name == 'create' %}
    <h1>NEW board</h1>
{% else %}
    <h1>EDIT board</h1>
{% endif %}

<!-- 1 -->
<form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit"/>
</form>

<!-- 2 -->
<!--<form method="POST">-->
<!--    {# csrf_token #}-->
<!--    {# form.title #}-->
<!--    {# form.content #}-->
<!--    <input type="submit" value="Submit"/>-->
<!--</form>-->

<!-- 3 -->
<!--<form method="POST">-->
<!--    {# csrf_token #}-->
<!--    {# for field in form #}-->
<!--        {# field.errors }}-->
<!--        {# field.label_tag #} {# field #}-->
<!--    {# endfor %}-->
<!--    <input type="submit" value="Submit"/>-->
<!--</form>-->

<!-- 4 -->
<!--{# form.non_field_errors #}-->
<!--<form method="POST">-->
<!--    {# csrf_token #}-->
<!--    <div class="col-4">-->
<!--        {# form.title.errors #}-->
<!--        {# form.title.label_tag #}-->
<!--        {# form.title #}-->
<!--    </div>-->
<!--    <div>-->
<!--        {# form.content.errors #}-->
<!--        {# form.content.label_tag #}-->
<!--        {# form.content #}-->
<!--    </div>-->
<!--    <input type="submit" value="Submit"/>-->
<!--</form>-->

<!-- 5 -->
{# crispy form #}


























{% if request.resolver_match.url_name == 'create' %}
    <a href="{% url 'boards:index' %}">BACK</a>
{% else %}
    <a href="{% url 'boards:detail' board.pk %}">BACK</a>
{% endif %}

{% endblock %}

boards/templates/boards/index.html
{% extends 'boards/base.html' %}
{% block body %}
<h1>게시글 목록</h1>
{% if user.is_authenticated %}
    <a href="{% url 'boards:create' %}">새 글 작성</a>
{% else %}
    <a href="{% url 'accounts:login' %}">새 글을 작성하려면 로그인 하세요.</a>
{% endif %}
<hr>
{% for board in boards %}
    <p><b>작성자 <a href="{% url 'accounts:profile' board.user_id %}">{{ board.user }}</a></b></p>
    <p>{{ board.pk }}</p>
    <p>{{ board.title }}</p>
    <a href="{% url 'boards:detail' board.pk %}">글 보러가기</a>
    <hr>
{% endfor %}
{% endblock %}