accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('profile/<int:user_pk>/', views.profile, name='profile'),
    path('password/', views.change_password, name='change_password'),
    path('edit/', views.edit, name='edit'),
    path('delete/', views.delete, name='delete'),
    path('logout/', views.logout, name='logout'),
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),    
]

boards/urls.py
from django.urls import path
from . import views

app_name = 'boards'

urlpatterns = [
    path('<int:board_pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),    
    path('<int:board_pk>/comments/', views.comment_create, name='comment_create'),    
    path('<int:board_pk>/edit/', views.update, name='update'),    
    path('<int:board_pk>/delete/', views.delete, name='delete'),    
    path('<int:board_pk>/', views.detail, name='detail'),    
    path('new/', views.create, name='create'),    
    path('', views.index, name='index'),    
]

myform/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('boards/', include('boards.urls')),
    path('admin/', admin.site.urls),
]

accounts/models.py
from django.db import models

# Create your models here.

boards/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Board(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f'Board{self.pk}'
        # return self.title

class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    content = models.CharField(max_length=140)
    
    def __str__(self):
        return self.content

accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth import get_user_model

class UserCustomChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ['email', 'first_name', 'last_name',]
        
class UserCustomCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'password1', 'password2', 'email',]
        # fields = ['username', 'email',]

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import update_session_auth_hash, get_user_model
from .forms import UserCustomChangeForm, UserCustomCreationForm

# Create your views here.
def signup(request):
    if request.user.is_authenticated:
        return redirect('boards:index')
    
    if request.method == 'POST':
        form = UserCustomCreationForm(request.POST)
        if form.is_valid():
            user = form.save()              # 1
            auth_login(request, user)       # 2
            return redirect('boards:index')
    else:
        form = UserCustomCreationForm()
    context = {'form': form}
    return render(request, 'accounts/auth_form.html', context)


def login(request):
    if request.user.is_authenticated:
        return redirect('boards:index')
        
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.POST.get('next') or 'boards:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
        'next': request.GET.get('next', ''),
    }
    return render(request, 'accounts/login.html', context)


def logout(request):
    auth_logout(request)
    return redirect('boards:index')

def delete(request):
    user = request.user
    if request.method == 'POST':
        user.delete() 
    return redirect('boards:index')

def edit(request):
    if request.method == 'POST':
        form = UserCustomChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('boards:index')
    else:
        form = UserCustomChangeForm(instance=request.user)
    context = {'form': form,}
    return render(request, 'accounts/auth_form.html', context)

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST) # 인자 순서 유의
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user) # 현재 유저가 로그아웃 되는 것을 막는다.
            return redirect('boards:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {'form': form,}
    return render(request, 'accounts/auth_form.html', context)

def profile(request, user_pk):
    user_info = get_object_or_404(get_user_model(), pk=user_pk)
    context = {
        'user_info': user_info
    }
    return render(request, 'accounts/profile.html', context)

accounts/templates/accounts/auth_form.html
{% extends 'boards/base.html' %}
{% block body %}
{% load crispy_forms_tags %}

{% if request.resolver_match.url_name == 'signup' %}
    <h1>회원가입</h1>
{% elif request.resolver_match.url_name == 'edit'%}
    <h1>회원수정</h1>
{% else %}
    <h1>비밀번호 변경</h1>
{% endif %}

<form action="" method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="submit"/>
</form>
{% endblock %}

accounts/templates/accounts/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    <div class="container">
        {% if user.is_authenticated %}
            <h1>
                <a href="{% url 'accounts:logout' %}">[로그아웃]</a>
            </h1>
        {% else %}
            <h1>
                <a href="{% url 'accounts:login' %}">[로그인]</a>
                <a href="{% url 'accounts:signup' %}">[회원가입]</a>
            </h1>
        {% endif %}
        <hr>
        {% block body %}
        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

accounts/templates/accounts/change_password.html
{% extends 'boards/base.html' %}
{% block body %}
{% load crispy_forms_tags %}
<h1>비밀번호 변경</h1>
<form action="" method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="submit"/>
</form>
{% endblock %}

accounts/templates/accounts/edit.html
{% extends 'boards/base.html' %}
{% block body %}
{% load crispy_forms_tags %}
<h1>회원 수정</h1>
<form action="" method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="submit"/>
</form>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'boards/base.html' %}
{% block body %}
{% load crispy_forms_tags %}
<h1>로그인</h1>
<form action="" method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="submit"/>
    <input type="hidden" value="{{ next }}" name="next"/>
</form>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'accounts/base.html' %}
{% block body %}
{% load gravatar %}

<h2><img src="https://s.gravatar.com/avatar/{{ user_info.email|makemd5 }}?s=80" alt="profile img"> {{ user_info.username }}의 프로필</h2>
<h3>{{ user_info.username }}가 작성한 게시글</h3>
{% if user == user_info %}
    <a href="{% url 'accounts:edit' %}">[내정보 수정]</a>
    <a href="{% url 'accounts:change_password' %}">[비번변경]</a>
    <form action="{% url 'accounts:delete' %}" method="POST" style="display: inline;">
        {% csrf_token %}
        <input type="submit" value="탈퇴">
    </form>
{% endif %}

<hr>


{% for board in user_info.board_set.all %}
    제목 : {{ board.title }}
    내용 : {{ board.content }}
    달린 댓글 수 : {{ board.comment_set.all | length }}
    <hr>
{% endfor %}
<hr>
<h3>{{ user_info.username }}가 작성한 댓글들</h3>
{% for comment in user_info.comment_set.all %}
    <div>{{ comment }} - <a href="{% url 'boards:detail' comment.board_id %}">{{ comment.board }}</a></div>
{% endfor %}


{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'boards/base.html' %}
{% block body %}
{% load crispy_forms_tags %}
<h1>회원가입</h1>
<form action="" method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="submit"/>
</form>

{% endblock %}